Yarab 3l4han T3bt

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -51,12 +51,16 @@ jobs:
       run: |
         aws s3 ls s3://${{ secrets.S3_BUCKET_PUBLIC }}/ | awk '{print $4}' | while read file; do
           if [[ $file == app_*.tar.gz ]]; then
-            build_date=$(echo $file | sed 's/app_\([0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}\).tar.gz/\1/')
-            build_timestamp=$(date -d $build_date +%s)
-            current_timestamp=$(date +%s)
-            diff=$(( (current_timestamp - build_timestamp) / 86400 ))
-            if [[ $diff -gt 7 ]]; then
-              aws s3 rm s3://${{ secrets.S3_BUCKET_PUBLIC }}/$file
+            build_date=$(echo $file | sed -n 's/app_\([0-9]*-[0-9]*-[0-9]*\)\.tar\.gz/\1/p')
+            if [ -n "$build_date" ]; then
+              build_timestamp=$(date -d "$build_date" +%s 2>/dev/null || echo "invalid")
+              if [ "$build_timestamp" != "invalid" ]; then
+                current_timestamp=$(date +%s)
+                diff=$(( (current_timestamp - build_timestamp) / 86400 ))
+                if [[ $diff -gt 7 ]]; then
+                  aws s3 rm s3://${{ secrets.S3_BUCKET_PUBLIC }}/$file
+                fi
+              fi
             fi
           fi
         done
